server:
  port: 8769

spring:
  application:
    name: server-admin
  boot:
    admin:
      ui:
        title: Spring Boot Admin
  security:
    user.name: admin
    user.password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    # 配置eureka认证 否则服务启动后一直为DOWN
    metadata-map:
      user.name: admin
      user.password: 123456
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${eureka.instance.metadata-map.user.name}:${eureka.instance.metadata-map.user.password}@localhost:8761/eureka/